# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Projects/Hackster_motor_ultrasonic/Hackster_motor_ultrasonic.srcs/sources_1/bd/Block_Design/ip/Block_Design_auto_pc_0/Block_Design_auto_pc_0.xci
# IP: The module: 'Block_Design_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Projects/Hackster_motor_ultrasonic/Hackster_motor_ultrasonic.srcs/sources_1/bd/Block_Design/ip/Block_Design_auto_pc_0/Block_Design_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Block_Design_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/Projects/Hackster_motor_ultrasonic/Hackster_motor_ultrasonic.srcs/sources_1/bd/Block_Design/ip/Block_Design_auto_pc_0/Block_Design_auto_pc_0.xci
# IP: The module: 'Block_Design_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Projects/Hackster_motor_ultrasonic/Hackster_motor_ultrasonic.srcs/sources_1/bd/Block_Design/ip/Block_Design_auto_pc_0/Block_Design_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Block_Design_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
