# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/io.xdc

# Block Designs: bd/Block_Design/Block_Design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Block_Design || ORIG_REF_NAME==Block_Design} -quiet] -quiet

# IP: bd/Block_Design/ip/Block_Design_processing_system7_0_0/Block_Design_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Block_Design_processing_system7_0_0 || ORIG_REF_NAME==Block_Design_processing_system7_0_0} -quiet] -quiet

# IP: bd/Block_Design/ip/Block_Design_Ultrasonic_IP_0_0/Block_Design_Ultrasonic_IP_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Block_Design_Ultrasonic_IP_0_0 || ORIG_REF_NAME==Block_Design_Ultrasonic_IP_0_0} -quiet] -quiet

# IP: bd/Block_Design/ip/Block_Design_ps7_0_axi_periph_0/Block_Design_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Block_Design_ps7_0_axi_periph_0 || ORIG_REF_NAME==Block_Design_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/Block_Design/ip/Block_Design_rst_ps7_0_50M_0/Block_Design_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Block_Design_rst_ps7_0_50M_0 || ORIG_REF_NAME==Block_Design_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/Block_Design/ip/Block_Design_auto_pc_0/Block_Design_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Block_Design_auto_pc_0 || ORIG_REF_NAME==Block_Design_auto_pc_0} -quiet] -quiet

# XDC: bd/Block_Design/Block_Design_ooc.xdc
